import { z } from "zod";
import type { McpServer } from "@modelcontextprotocol/sdk/server/mcp.js";
import type { ToolContext } from "../context.js";

export function registerInsightTools(server: McpServer, ctx: ToolContext): void {
  server.registerTool("list_insights", {
    description:
      "List structured insights generated by reflect or promoted from discoveries. " +
      "Insights are first-class knowledge objects with type, confidence, source entities, and lifecycle (active/archived/dismissed). " +
      "Returns active insights by default, content truncated to 200 chars.",
    inputSchema: {
      type: z.enum(["synthesis", "pattern", "anomaly", "bridge"]).optional().describe("Filter by insight type"),
      status: z.enum(["active", "archived", "dismissed"]).optional().default("active").describe("Filter by status"),
      sourceType: z.enum(["reflect", "discovery", "manual"]).optional().describe("Filter by source"),
      limit: z.number().optional().default(10).describe("Max results"),
      offset: z.number().optional().default(0).describe("Pagination offset"),
    },
  }, async ({ type, status, sourceType, limit, offset }) => {
    const rows = ctx.insights.listInsights({ type, status, sourceType, limit: limit ?? 10, offset: offset ?? 0 });

    const insights = rows.map(r => ({
      id: r.id,
      type: r.type,
      content: r.content.length > 200 ? r.content.slice(0, 200) + "..." : r.content,
      confidence: r.confidence,
      source_entities: r.source_entities ? JSON.parse(r.source_entities) : [],
      source_type: r.source_type,
      created_at: r.created_at,
    }));

    return {
      content: [{
        type: "text" as const,
        text: JSON.stringify({ insights, total: insights.length }, null, 2),
      }],
    };
  });

  server.registerTool("get_insight", {
    description: "Get full insight details by ID, including content and linked source entities.",
    inputSchema: {
      id: z.number().describe("Insight ID"),
    },
  }, async ({ id }) => {
    const row = ctx.insights.getInsight(id);
    if (!row) {
      return {
        content: [{ type: "text" as const, text: JSON.stringify({ error: `Insight #${id} not found` }) }],
        isError: true,
      };
    }

    const sourceEntities: string[] = row.source_entities ? JSON.parse(row.source_entities) : [];
    const entitySummaries = sourceEntities.slice(0, 10).map(slug => {
      const page = ctx.db.getPage(slug);
      return page ? { slug, title: page.title, type: page.type } : { slug, title: "(deleted)", type: "unknown" };
    });

    return {
      content: [{
        type: "text" as const,
        text: JSON.stringify({
          id: row.id,
          type: row.type,
          content: row.content,
          confidence: row.confidence,
          source_entities: entitySummaries,
          source_type: row.source_type,
          status: row.status,
          created_at: row.created_at,
          expires_at: row.expires_at,
          seen: row.seen,
        }, null, 2),
      }],
    };
  });

  server.registerTool("archive_insight", {
    description: "Archive an insight. Archived insights are soft-deleted from active results.",
    inputSchema: {
      id: z.number().describe("Insight ID to archive"),
    },
  }, async ({ id }) => {
    const ok = ctx.insights.archiveInsight(id);
    return {
      content: [{
        type: "text" as const,
        text: JSON.stringify({ success: ok, id, action: "archived" }),
      }],
    };
  });

  server.registerTool("dismiss_insight", {
    description: "Dismiss an insight as not useful. Dismissed insights won't appear in active results.",
    inputSchema: {
      id: z.number().describe("Insight ID to dismiss"),
    },
  }, async ({ id }) => {
    const ok = ctx.insights.dismissInsight(id);
    return {
      content: [{
        type: "text" as const,
        text: JSON.stringify({ success: ok, id, action: "dismissed" }),
      }],
    };
  });

  server.registerTool("query_insights", {
    description:
      "Semantic search over insights. Finds insights whose content is semantically similar to the query. " +
      "Only returns active insights. Use this when the user asks about patterns, trends, or connections in their knowledge.",
    inputSchema: {
      query: z.string().describe("Search query — natural language description of what to find"),
      limit: z.number().optional().default(5).describe("Max results"),
    },
  }, async ({ query, limit }) => {
    const rows = await ctx.insights.queryInsights(query, limit ?? 5);

    const insights = rows.map(r => ({
      id: r.id,
      type: r.type,
      content: r.content.length > 200 ? r.content.slice(0, 200) + "..." : r.content,
      confidence: r.confidence,
      source_type: r.source_type,
      created_at: r.created_at,
    }));

    return {
      content: [{
        type: "text" as const,
        text: JSON.stringify({ insights, query, total: insights.length }, null, 2),
      }],
    };
  });

  server.registerTool("promote_discovery", {
    description:
      "将结构发现升级为结构化洞察。Agent 或用户审核发现后确认值得保留时使用。" +
      "如果发现有 LLM 生成的建议，会自动用做洞察内容。",
    inputSchema: {
      discoveryId: z.number().describe("ID of the discovery to promote"),
      content: z.string().optional().describe("Override content — if omitted, uses suggestion or auto-generated"),
      type: z.enum(["synthesis", "pattern", "anomaly", "bridge"]).optional().default("bridge").describe("Insight type"),
      confidence: z.number().optional().describe("Confidence score (0-1). Default from discovery score."),
    },
  }, async ({ discoveryId, content, type, confidence }) => {
    const discovery = ctx.db.getDiscoveryById(discoveryId);
    if (!discovery) {
      return {
        content: [{ type: "text" as const, text: JSON.stringify({ error: `Discovery #${discoveryId} not found` }) }],
        isError: true,
      };
    }

    const entities: string[] = JSON.parse(discovery.entities);
    const defaultContent = discovery.suggestion
      ?? `结构发现：${entities.join(" 与 ")} 之间存在${discovery.type === "bridge" ? "桥接" : discovery.type === "community_crossing" ? "跨社区" : "结构洞"}关系（图距离 ${discovery.detail ? (JSON.parse(discovery.detail) as { distance?: number }).distance ?? "?" : "?"}）。`;
    const insightContent = content ?? defaultContent;

    const row = await ctx.insights.createInsight({
      content: insightContent,
      type: type ?? "bridge",
      confidence: confidence ?? discovery.score,
      sourceEntities: entities,
      sourceType: "discovery",
    });

    ctx.db.markDiscoverySeen(discoveryId);

    return {
      content: [{
        type: "text" as const,
        text: JSON.stringify({
          success: true,
          insight: { id: row.id, content: row.content, type: row.type, confidence: row.confidence },
          promoted_from: discoveryId,
          actionable: discovery.actionable,
          had_suggestion: !!discovery.suggestion,
        }, null, 2),
      }],
    };
  });
}
