import type { McpServer } from "@modelcontextprotocol/sdk/server/mcp.js";
import type { ToolContext } from "./context.js";
import { registerSearchTools } from "./tools/search.js";
import { registerIngestTools } from "./tools/ingest.js";
import { registerPageTools } from "./tools/pages.js";
import { registerGraphTools } from "./tools/graph.js";
import { registerTagTools } from "./tools/tags.js";
import { registerTimelineTools } from "./tools/timeline.js";
import { registerVersionTools } from "./tools/versions.js";
import { registerJobTools } from "./tools/jobs.js";
import { registerSyncTools } from "./tools/sync.js";
import { registerOpsTools } from "./tools/ops.js";
import { registerRecallTools } from "./tools/recall.js";
import { registerBrainstormTools } from "./tools/brainstorm.js";
import { registerSummarizeTools } from "./tools/summarize.js";
import { registerDiscoveryTools } from "./tools/discoveries.js";
import { registerInsightTools } from "./tools/insights.js";
import { registerExpandTools } from "./tools/expand.js";
import { registerProfileTools } from "./tools/profile.js";
import { registerDossierTools } from "./tools/dossier.js";
import { registerHierarchyTools } from "./tools/hierarchy.js";
import { registerFeedbackTools } from "./tools/feedback.js";
import { registerBatchTools } from "./tools/batch.js";
import { registerProvenanceTools } from "./tools/provenance.js";
import { registerEpisodeTools } from "./tools/episode.js";
import { registerAgenticResearchTools } from "./tools/agentic-research.js";

export function registerAllTools(server: McpServer, ctx: ToolContext): void {
  registerSearchTools(server, ctx);
  registerIngestTools(server, ctx);
  registerPageTools(server, ctx);
  registerGraphTools(server, ctx);
  registerTagTools(server, ctx);
  registerTimelineTools(server, ctx);
  registerVersionTools(server, ctx);
  registerJobTools(server, ctx);
  registerSyncTools(server, ctx);
  registerOpsTools(server, ctx);
  registerRecallTools(server, ctx);
  registerBrainstormTools(server, ctx);
  registerSummarizeTools(server, ctx);
  registerDiscoveryTools(server, ctx);
  registerInsightTools(server, ctx);
  registerExpandTools(server, ctx);
  registerProfileTools(server, ctx);
  registerDossierTools(server, ctx);
  registerHierarchyTools(server, ctx);
  registerFeedbackTools(server, ctx);
  registerBatchTools(server, ctx);
  registerProvenanceTools(server, ctx);
  registerEpisodeTools(server, ctx);
  registerAgenticResearchTools(server, ctx);
}
