import { CBrainDB } from "../storage/sqlite.js";
import type { PageManager } from "./page.js";
import type { GraphManager } from "./graph/graph.js";
import type { LLMProvider } from "../llm/provider.js";
import type { ContentPipeline } from "./ingestion/pipeline.js";
import type { Logger } from "./logger.js";
import { getHierarchyContext } from "./graph/hierarchy.js";

const DOSSIER_OPEN = "<!-- cbrain-dossier -->";
const DOSSIER_CLOSE = "<!-- /cbrain-dossier -->";

export interface DossierDeps {
  db: CBrainDB;
  pages: PageManager;
  graph: GraphManager;
  llm: LLMProvider;
  pipeline: ContentPipeline;
  logger?: Logger;
}

export interface DossierResult {
  slug: string;
  title: string;
  dossier: string;
  generated_at: string;
}

/**
 * Extract existing dossier section from page body, or null if none.
 */
export function extractDossier(body: string): string | null {
  const openIdx = body.indexOf(DOSSIER_OPEN);
  if (openIdx === -1) return null;
  const closeIdx = body.indexOf(DOSSIER_CLOSE, openIdx);
  if (closeIdx === -1) return null;
  return body.slice(openIdx + DOSSIER_OPEN.length, closeIdx).trim();
}

/**
 * Check if a page has a dossier and whether it's fresh (< maxAgeDays old).
 */
export function isDossierFresh(
  frontmatter: Record<string, unknown>,
  maxAgeDays: number = 7,
): { has: boolean; fresh: boolean; updatedAt: string | null } {
  const ts = frontmatter.dossier_updated as string | undefined;
  if (!ts) return { has: false, fresh: false, updatedAt: null };
  const age = Date.now() - new Date(ts).getTime();
  const fresh = age < maxAgeDays * 86_400_000;
  return { has: true, fresh, updatedAt: ts };
}

/**
 * Replace or append the dossier section in page body.
 */
function injectDossier(body: string, dossier: string, title: string, date: string): string {
  const openIdx = body.indexOf(DOSSIER_OPEN);
  const closeIdx = body.indexOf(DOSSIER_CLOSE, openIdx !== -1 ? openIdx : 0);

  const section = `${DOSSIER_OPEN}\n## ${title} 档案\n\n${dossier}\n\n_Generated by CBrain dossier — ${date}_\n${DOSSIER_CLOSE}`;

  if (openIdx !== -1 && closeIdx !== -1) {
    return body.slice(0, openIdx) + section + body.slice(closeIdx + DOSSIER_CLOSE.length);
  }

  return `${body.trimEnd()}\n\n${section}\n`;
}

/**
 * Generate a structured dossier for an entity: read all data, LLM synthesis, write back.
 */
export async function generateDossier(
  slug: string,
  deps: DossierDeps,
): Promise<DossierResult> {
  const { db, pages, graph, llm, pipeline, logger } = deps;

  const page = pages.getBySlug(slug);
  if (!page) throw new Error(`实体不存在: ${slug}`);

  // 1. Gather all data (strip previous dossier from chunks to avoid circular reasoning)
  const rawChunks = db.getChunksByPage(slug)
    .map(c => stripDossier(c.content))
    .filter(c => c.trim().length > 0);

  const allLinks = graph.getLinks(slug, "both");
  const outgoing = allLinks.filter(l => l.from_slug === slug);
  const incoming = allLinks.filter(l => l.to_slug === slug);

  const rawTimeline = db.getTimeline(slug) as Array<{
    summary: string; event_date: string | null; source: string | null;
  }>;

  const related = graph.getRelatedEntities(slug, 10);
  const tags = db.getTags(slug);
  const hierarchy = getHierarchyContext(slug, { pages, graph });

  // External perspective: chunks from other pages that mention this entity
  const entityName = page.title;
  const externalChunks: string[] = [];
  const externalSlugs = [...new Set(incoming.map(l => l.from_slug))].filter(s => s !== slug);
  for (const s of externalSlugs.slice(0, 8)) {
    const sourceName = s.replace(/^brain\/(?:entities|concepts|records)\//, "");
    const sourceChunks = db.getChunksByPage(s)
      .map(c => stripDossier(c.content))
      .filter(c => c.includes(entityName) || c.includes(slug.split("/").pop()!))
      .slice(0, 2);
    for (const c of sourceChunks) {
      externalChunks.push(`[${sourceName} 的视角] ${c}`);
    }
  }

  // 2. Build context for LLM (strip dossier from body to avoid circular reasoning)
  const chunkText = rawChunks.length > 0
    ? rawChunks.map((c, i) => `[片段${i + 1}] ${c}`).join("\n\n")
    : "(无内容片段)";

  const externalText = externalChunks.length > 0
    ? externalChunks.join("\n\n")
    : "(无外部视角数据)";

  const linkText = [
    ...outgoing.map(l => `- ${page.title} → ${l.to_slug.replace(/^brain\/entities\//, "")} (${l.relation}, 强度: ${l.strength}${l.context ? `, 上下文: ${l.context.slice(0, 80)}` : ""})`),
    ...incoming.map(l => `- ${l.from_slug.replace(/^brain\/entities\//, "")} → ${page.title} (${l.relation}, 强度: ${l.strength}${l.context ? `, 上下文: ${l.context.slice(0, 80)}` : ""})`),
  ].join("\n") || "(无关联关系)";

  const timelineText = rawTimeline.length > 0
    ? rawTimeline.map(t => `- ${t.event_date ?? "未知日期"}: ${t.summary}`).join("\n")
    : "(无时间线事件)";

  const relatedText = related.length > 0
    ? related.map(r => `- [[${r.slug}]] (${r.title}, ${r.type})`).join("\n")
    : "(无相关实体)";

  const tagsText = tags.length > 0 ? tags.join(", ") : "(无标签)";
  const cleanBody = stripDossier(page.body ?? "");
  const bodyText = cleanBody ? cleanBody.slice(0, 1000) : "(无正文)";

  // Hierarchy text
  const hierarchyParts: string[] = [];
  if (hierarchy.reports_to) {
    hierarchyParts.push(`- 直属上级: ${hierarchy.reports_to_title ?? hierarchy.reports_to}`);
  }
  if (hierarchy.subordinates.length > 0) {
    hierarchyParts.push(`- 直属下级: ${hierarchy.subordinates.map(s => s.title).join(", ")}`);
  }
  if (hierarchy.peers.length > 0) {
    hierarchyParts.push(`- 同级: ${hierarchy.peers.map(s => s.title).join(", ")}`);
  }
  const hierarchyText = hierarchyParts.length > 0 ? hierarchyParts.join("\n") : "(未设置组织层级)";

  // 3. LLM prompt
  const prompt = `你是一位资深情报分析师，擅长从碎片化信息中提炼结构化判断。

任务：为实体"${page.title}"生成一份深度分析档案。不是简单摘要——是基于所有可用数据的综合研判。

## 可用数据

### 基本信息
- 标题: ${page.title}
- 类型: ${page.frontmatter.type}
- 标签: ${tagsText}
- 提及次数: ${page.mention_count}

### 正文摘要
${bodyText}

### 原始内容片段（${rawChunks.length} 条）
${chunkText}

### 外部视角（其他页面如何描述 ${page.title}，${externalChunks.length} 条）
${externalText}

### 关联关系（${outgoing.length + incoming.length} 条，箭头表示提及方向，不代表组织层级）
${linkText}

### 组织层级（明确设定的上下级关系，非推断）
${hierarchyText}

### 时间线（${rawTimeline.length} 条事件）
${timelineText}

### 相关实体
${relatedText}

---

## 输出要求

以 JSON 格式输出，字段 "dossier" 包含 Markdown 文本（不要用代码块包裹），严格按以下结构，每部分都要有实质内容，不要一笔带过：

### 核心定位
用 2-3 句话从多个角度定位：这个实体是什么、在知识网络中扮演什么角色、核心价值或特征是什么。不要只写一句话。

### 关键能力/特征
列出 3-5 条核心特征，每条要求：
- 先给结论（这个实体能做什么 / 是什么性质）
- 再用具体数据佐证（引用 [[slug]] 作为来源）
- 如果多条记录支持同一特征，合并分析并标注所有来源

### 信息矛盾与风险标记
逐条检查数据中是否存在：
- 同一主题的矛盾信息（不同来源说法不一致）
- 时间线上的异常（突然出现/消失/频率异常）
- 关系网络中的异常模式（强度异常、方向异常）
- 言行不一致的信号（说了X但做了Y）
如果确实没有风险信号，写"当前数据量不足以识别明确风险（共 ${rawChunks.length} 条记录）"

### 关键关系网络
分析最重要的 3-5 个关联实体，对每个关系说明：
- 关系性质（合作/竞争/从属/影响等）
- 关系强度和方向
- 这个关系对该实体意味着什么

### 数据充分度与可信度
- 数据量：${rawChunks.length} 条记录 + ${rawTimeline.length} 条时间线 + ${outgoing.length + incoming.length} 个关联
- 时间覆盖范围评估
- 信息一致性判断
- 关键信息缺口（还缺什么数据才能做更准确的判断）

## 分析规则
- 全部中文
- 基于提供的数据做分析。可以基于数据做合理推断，但推断部分要标注（推断）
- 每个判断必须标注来源 [[slug]]
- "组织层级"部分是明确设定的事实，可以直接引用。上级/下级/同级关系不需要推断
- 关联关系中的箭头仅表示"A的页面提及了B"，不代表上下级或组织层级——层级关系以"组织层级"部分为准。如果关系类型是"提及"，就写"提及/关联"，不要擅自改成"上级"、"下属"等层级词
- 输出格式：{"dossier": "完整的 Markdown 文本"}
- dossier 字段内容不少于 500 字`;

  // 4. Call LLM
  const raw = await llm.chat([{ role: "user", content: prompt }]);
  let dossier = parseDossierResponse(raw);

  // 5. Validate + retry once if needed
  const validation = validateDossier(dossier, { chunkCount: rawChunks.length, linkCount: outgoing.length + incoming.length });
  if (!validation.ok) {
    logger?.warn("dossier", "首次生成未通过质量检查，重试", { slug, issues: validation.issues });
    const retryPrompt = `${prompt}\n\n⚠️ 上次输出未通过质量检查：${validation.issues.join("；")}。必须严格按结构要求输出，每段都要有实质内容。`;
    const retryRaw = await llm.chat([{ role: "user", content: retryPrompt }]);
    const retryDossier = parseDossierResponse(retryRaw);
    const retryValidation = validateDossier(retryDossier, { chunkCount: rawChunks.length, linkCount: outgoing.length + incoming.length });
    if (retryValidation.ok) {
      dossier = retryDossier;
    }
  }

  // 6. Write back to page
  const now = new Date().toISOString();
  const strippedBody = stripDossier(page.body ?? "");
  const newBody = injectDossier(strippedBody, dossier, page.title, now.slice(0, 10));

  pages.update(slug, {
    body: newBody,
    extra: { dossier_updated: now },
  });

  // 7. Re-index chunks (body changed)
  try {
    const { chunks: newChunks, embedResults } = await pipeline.embed(newBody);
    await pipeline.writeIndexes(slug, newChunks, embedResults);
  } catch (e) {
    logger?.warn("dossier", "重新索引失败", { slug, error: String(e) });
  }

  logger?.info("dossier", "档案已生成", { slug, title: page.title });

  return { slug, title: page.title, dossier, generated_at: now };
}

function parseDossierResponse(raw: string): string {
  try {
    const parsed = JSON.parse(raw);
    return (typeof parsed === "string" ? parsed : parsed.dossier ?? raw).trim();
  } catch {
    return raw.replace(/^```(?:markdown|md)?\n?/m, "").replace(/\n?```\s*$/m, "").trim();
  }
}

const REQUIRED_SECTIONS = [
  "### 核心定位",
  "### 关键能力",
  "### 信息矛盾",
  "### 关键关系",
  "### 数据充分度",
];

function validateDossier(
  dossier: string,
  data: { chunkCount: number; linkCount: number },
): { ok: boolean; issues: string[] } {
  const issues: string[] = [];

  const lines = dossier.split("\n");
  const headings = new Set(lines.filter(l => l.startsWith("### ")).map(l => l.trim()));
  for (const required of REQUIRED_SECTIONS) {
    if (![...headings].some(h => h.startsWith(required))) {
      issues.push(`缺少段落"${required}"`);
    }
  }

  const textOnly = dossier.replace(/[^\p{L}\p{N}]/gu, "");
  if (textOnly.length < 500) {
    issues.push(`内容过短（${textOnly.length} 字，要求 >= 500）`);
  }

  if (data.chunkCount > 5) {
    const citations = (dossier.match(/\[\[/g) ?? []).length;
    if (citations < 3) {
      issues.push(`来源引用不足（${citations} 个 [[ 引用，要求 >= 3）`);
    }
  }

  return { ok: issues.length === 0, issues };
}

function stripDossier(body: string): string {
  const openIdx = body.indexOf(DOSSIER_OPEN);
  if (openIdx === -1) return body;
  const closeIdx = body.indexOf(DOSSIER_CLOSE, openIdx);
  if (closeIdx === -1) return body;
  return (body.slice(0, openIdx) + body.slice(closeIdx + DOSSIER_CLOSE.length)).trimEnd();
}
